# Effective Kafka broker configuration for kafka-0.
broker.id=0
zookeeper.connect=zookeeper:2181
listeners=INTERNAL_SSL://0.0.0.0:9093,EXTERNAL_SSL://0.0.0.0:19092
advertised.listeners=INTERNAL_SSL://kafka-0:9093,EXTERNAL_SSL://localhost:19092
inter.broker.listener.name=INTERNAL_SSL
listener.security.protocol.map=INTERNAL_SSL:SSL,EXTERNAL_SSL:SSL
ssl.keystore.filename=kafka-0.keystore.jks
ssl.truststore.filename=kafka-0.truststore.jks
ssl.client.auth=required
ssl.endpoint.identification.algorithm=https
ssl.principal.mapping.rules=RULE:^CN=([^,]+).*$/$1/,DEFAULT
authorizer.class.name=kafka.security.authorizer.AclAuthorizer
allow.everyone.if.no.acl.found=false
