security.protocol=SSL
ssl.truststore.location=/etc/kafka/secrets/client.truststore.jks
ssl.truststore.password=password
ssl.truststore.type=JKS
ssl.keystore.location=/etc/kafka/secrets/admin.keystore.jks
ssl.keystore.password=password
ssl.key.password=password
ssl.keystore.type=JKS
ssl.endpoint.identification.algorithm=https
